[package]
name = "types"
version = "0.1.0"
edition = "2024"

[dependencies]
jiff = { version = "0.2.15", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_bytes = "0.11.19"
serde_repr = "0.1.20"
ts-rs = "11.1.0"
