[package]
name = "tokape"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
# chrono = { version = "0.4", features = ["clock"] }
comemo = "0.5.0"
jiff = { version = "0.2.15", features = ["serde"] }
thiserror = "2"
typst = "0.13.1"
typst-pdf = "0.13.1"
