// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Query = { key: number, question: string, revelation: string, answer: string | null, comment: string | null, subflow: Array<Query>, skippable: boolean, visible: boolean, };
